spring.application.name=pedidos

# H2 - base de datos en memoria
spring.datasource.url=jdbc:h2:mem:pedidosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Circuit Breaker (Resilience4j)
resilience4j.circuitbreaker.instances.pedidos.sliding-window-size=5
resilience4j.circuitbreaker.instances.pedidos.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.pedidos.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.pedidos.permitted-number-of-calls-in-half-open-state=3
